### PR TITLE
Updates required for gravitron

### PR DESCRIPTION
**Pull request by jaredly**
Here's what I've got :D but I don't really have the stamina to break it up into small things right now...

Changes
- [x] support multi-file hot reloading
- [x] add `Reprocessing.target = Reasongl.Gl.target`
- [x] add `Env.maxWidth(env)` (& height) which gives the maximum width / height of the screen
  - on web, this maps to window.innerWidth/Height
- [x] add a `title` attribute to the main `run()` function, which is used to set the title of the native window
- [x] add `backPressed` handling, which android uses. If the handler returns `None` then the android side knows it wasn't handled, and it will close the activity.
- [x] fix some line drawing of triangles & such
- [x] add `getTimeMs` so that games can track time
- [x] add `load/saveUserData` for saving arbitrary data
- [x] extend the hotreload matchenv to account for mobile native targets
- [x] use `fillTextureWithColor` instead of `texImage2D_RGBA` for creating the dummy texture, b/c I couldn't for the life of me get `texImage2D_RGBA` to work on android.

### CODE REVIEW

**Comment by Schmavery** [comment]
About to get on a plane so I'll make it quick for now and follow up later.
Looks like this is an update/continuation of your closed PR.

Some of this stuff I would hit merge immediately if given the option:
- triangle drawing fixes
- title attribute

Other stuff I feel is likely pretty close but maybe needs an api or naming tweak:
- getTimeMs() -> millis() to match https://processing.org/reference/millis_.html
- ?

Other stuff is probably good but I need a little bit to think about it / whether we can do it a better way.
- load/saveUserData 
- hotreload changes
- fillTexture
- backPressed
- maxWidth
- target

Sorry gotta run! haha

**Comment by Schmavery** [comment]
Ok here are my thoughts in more detail:
- Triangle fixes: let's get them in master ASAP because it's a bugfix that will help everyone!
- Title attribute + async init: I'm totally onboard to merge this as soon as we make the change to reasongl.

Other stuff:

#### maxWidth/Height
I'm tempted to say we should add a [fullscreen()](https://processing.org/reference/fullScreen_.html) instead **however** it might be just as good or better to provide a `displayWidth` and `displayHeight` as processing used to (now deprecated because of fullscreen() but maybe [still useful](https://forum.processing.org/two/discussion/12644/how-to-obtain-pixel-dimensions-of-screen-in-processing-3))

#### getTimeMs
Not sure what problem you're solving with this, I just looked at your reasongl-native PR and realized I misunderstood what you want it to do. What sort of "time tracking" do you want to do? I'd be happy if we added the [hour](https://processing.org/reference/hour_.html), [minute](https://processing.org/reference/minute_.html), [second](https://processing.org/reference/second_.html) apis to check the current time (along with day/month/year etc). For time tracking within a game, we offer the Env.deltaTime api to get the time of the last frame.  I wouldn't mind also providing the [millis()](https://processing.org/reference/millis_.html) api to give the time since starting the program.

#### Reprocessing.target
I'm conflicted over whether or not I would want this to be a thing. There are already a couple of possible ways to swap behaviors between platforms (functors, different entrypoints, ppx, bsc conditional compilation) and this is the most "at runtime" of all of them. Could be convinced with a good use-case, I guess.

#### Backpressed
I'd love to get some more context here. Is there a reason we need to have this special cased? I'm assuming it only ever gets triggered on Android and so I don't really see how you could write cross-platform behavior for this event. Is it not ok to simply close the app when this is pressed?

#### Multifile hotreloading
I tried to express some concerns with this and explain how I imagined this could be implemented back in https://github.com/Schmavery/reprocessing/pull/51. It would be great if you could speak to how the design has evolved since then.

#### fillTextureWithColor
Too bad we couldn't get texImage2D_RGBA to work on android for some reason, would be interested in more info on what happened here. Would be great if we could keep the reasongl apis consistent where possible.

#### load/saveUserData
This seems like a super great functionality to add, I guess we'll want to make sure it gets handled right on different platforms (i.e. where should application data be stored on mac vs android vs whatever). I looked quickly at the implementation in reasongl-native and saw it seems to just be writing to "user_data_<key>" files next to the binary (which is maybe good enough for now! not a blocker imo). Might want to escape the key etc etc but seems overall great!

**Comment by jaredly** [comment]
Ok. tbh I don't have a ton of incentive to get my changes upstreamed other than "it's the right thing to do". I've forked everything & it works for me, but I figure y'all will want cross-platform goodness as well.

- maxWidth/Height -- `fullscreen()` doesn't cover my use case -- I want to know what the max width/height is so that I can shrink the screen if it's too big, but only then
- load/saveUserData -- yes I handle all platforms. escaping the path sounds useful
- getTimeMs -- I want to track how long a user took to complete a level. hour/minute/second api's sounds overly tedious for what I want to do. milis() would work tho. `getTimeMs` was just the easiest thing for me to implement to get the functionality I wanted.
- Reprocessing.target -- I definitely want this to be a thing. conditional compilation/matchenv etc. feel like hacks to me for when you need to mess with performance or something
- Backpressed -- again, this is what it took to meet my needs. Yes it's not OK to just close the app -- games generally will pause when you press `back`, or if you're on a different screen it will take you to the initial screen. It needs to interact with the runloop, so the only way I could think of implementing it was this way.
- Multifile hotrelaoding -- this version is 100% backwards compatible. no differences in behavior or type signature
- fillTextureWithColor -- "keep the reasongl apis consistent where possible" we can just ditch `texImage2D_RGBA` because that was the only thing it was used for. With my changes, they are all consistent.

**Comment by Schmavery** [comment]
I appreciate you taking the time to submit this/follow up with answers to questions etc and totally get that this isn't your top priority. My commentary here is just as much me trying to make sense of all this great work you've done and trying to figure out where it can fit in design-wise.

Maybe it will work best if I do my best to upstream each of these features individually as it becomes clear how they will work best with the rest of reprocessing to save you the trouble of breaking them apart or making small changes here and there. Will try to put some more time into this in the near future.

**Pull request closed without merging**
