### PR TITLE
Make Reprocessing work with the latest bs-platform

### PR DESCRIPTION
**Pull request by bsansouci**
I finally found time to push this! We basically switch to depending only on reasongl-web, and there's no change needed otherwise. 
On the up side, this dramatically simplifies stuff :)

### CODE REVIEW

**Comment by phated** [comment]
Does this mean that native support will be dropped?

**Comment by bsansouci** [comment]
Yes, I've lost steam and had to confront the fact that I won't be able to continue pushing for bsb-native. I should've done it sooner if anything, but I don't want Reprocessing to come down with it because it's still an awesome library. The way I see it, native support was awesome and gave us lots of cool demos, but we never really fully leveraged it in the end. We exclusively used it for fast hot reloading, but shipped games compiled to JS. We did have a dream to make it fully functional for making iOS/Android games. So maybe one day someone could pick up from the work on bsb-native, and make something focused on releasing games for iOS (we have a branch of bsb-native and reprocessing that does work, and have a game almost 100% done actually, so we know it's doable: https://github.com/bsansouci/reprocessing-example-cross-platform/tree/fruits).

Super sorry for the churn <3

**Comment by Schmavery** [comment]
😢 it's been a good ride but too much work for us right now ❤️

**Comment by phated** [comment]
Makes sense! Thank you for all the great work!

**Pull request merged**
