### PR TITLE
Add "clear" to Draw's .rei

### PR DESCRIPTION
**Pull request by jaredly**
Must have been missed or something

### CODE REVIEW

**Comment by Schmavery** [comment]
I've been considering taking this out.  What do you need it for?

**Comment by jaredly** [comment]
Clear is just as valid though, right? On the web, for example, Clear gives you a transparent background.

**Comment by Schmavery** [comment]
Hmm, ok that's probably a fair point.  I'm a little concerned that this will increase the difference in behaviour between native and web (in native, clear makes the screen go black), but maybe I can add it back in for now and we can see how it goes.

**Comment by jaredly** [comment]
Thanks!

**Pull request closed without merging**
