### PR TITLE
Fix crash when opening native / bytecode without hotreloading.

### PR DESCRIPTION
**Pull request by bsansouci**
when not in hotreloading mode

### CODE REVIEW

**Comment by bsansouci** [comment]
Otherwise we get a unix error when trying to hotreload a file whose name is empty string [here](https://github.com/Schmavery/reprocessing/blob/7eb3e473382d64d4d33b80a3c2e0277c7f52921d/src/Reprocessing.re#L265)

**Comment by Schmavery** [comment]
Is it clear that we should be doing this instead of handling the empty string on the hotreloading end (and not attempting to recompile or something). I don't fully grasp the Hashtbl code right now. 

cc @jaredly

**Comment by bsansouci** [comment]
Ok fixed it checking the file name. That code path was always executing anyway (the one I removed) and empty string is probably a good default anyway.

**Comment by Schmavery** [comment]
lgtm

**Pull request merged**
