### PR TITLE
Upgrade to Reason 3 syntax

### PR DESCRIPTION
**Pull request by ryanartecona**
This is just from running the [reason 3 upgrade script](https://github.com/reasonml/upgradeSyntaxFrom2To3) on this repo.

It went mostly smoothly, but there was 1 hiccup that will need to be addressed. The `~val` named arg on [this line](https://github.com/ryanartecona/reprocessing/blob/reason-3/src/Reprocessing_Internal.re#L276) throws a new error under refmt3:

```
Error: 818: val is a reserved keyword, it cannot be used as an identifier. Try `val_' instead
```

I did try just changing it to `val_`, just in case, but it doesn't work.

This will need to be addressed upstream in reasongl-{interface,web,native} whenever those move to reason 3 (though I'm not quite sure why it worked in the first place).

### CODE REVIEW

**Comment by Schmavery** [comment]
Wow this is awesome, thanks! Will take a quick look at the val issue shortly.

**Comment by Schmavery** [comment]
Hey @ryanartecona, we fixed the val issue this weekend which unfortunately broke this PR, feel free to either fix it or I can do the conversion on my side.
For now I think we need to not convert the Reprocessing_Ext.re file as the web env needs some work before it can support refmt 3.

**Comment by ryanartecona** [comment]
Oh ok, no problem. By all means, feel free to take this over and do whatever you need to support the v3 syntax. I'm not tied to being the one to land the changes.

**Comment by Schmavery** [comment]
Should be closed by 6a193a923e4d7e2b7b9973da59907cc18d27aa15. Lmk if you have any issues!

**Pull request closed without merging**
